document.write("<div class=\"_headerBox\">");
document.write("  <div class=\"_navigation _width\">");
document.write("     <img src=\"./img/logo.png\" style=\"margin-right:10px;\">");
document.write("     <a href=\"\"  class=\"nav_li\">首页</a>");
document.write("     <a href=\"\" class=\"nav_li\" id=\"quotes_center\">行情中心</a>");
document.write("     <a href=\"\" class=\"nav_li\">24小时快讯</a>");
document.write("     <a href=\"\" class=\"nav_li\">专栏</a>");
document.write("     <a href=\"\" class=\"nav_li\">企业服务</a>");
document.write("     <div  class=\"fr _mar cp _avatar\" style=\"display:block;\"></div>");
document.write("     <div  class=\"fr _mar cp no_news\" style=\"display:none;\"></div>");
document.write("     <div  class=\"fr _mar cp has_news\" style=\"display:block;\"></div>");
document.write("     <div  class=\"fr cp _signin\" style=\"display:none;\"></div>");
document.write("     <div  class=\"fr _mar cp _login\" style=\"display:none;\"></div>");
document.write("     <div  class=\"fr _mar cp _khd\"></div>");
document.write("     <div  class=\"fr _mar cp _search\"></div>");
document.write("     <div class=\"_search_box\">");
document.write("        <img src=\"./img/icon_search.png\" class=\"icon_search cp\">");
document.write("        <input  class=\"ipt_text\" type=\"text\">");
document.write("        <img src=\"./img/close.png\" class=\"icon_close cp\">");
document.write("     </div>");
document.write("     <div class=\"avatar_pop\"></div>");
document.write("     <div class=\"news_pop\"></div>");
document.write("  </div>");
document.write("  <ul class=\"drop_down\" id=\"drop_down\">");
document.write("     <li class=\"line_right\">");
document.write("        <a href=\"\"><img src=\"./img/dxzf.png\"></a>");
document.write("     </li>");
document.write("     <li class=\"line_right\">");
document.write("        <a href=\"\"><img src=\"./img/mnjy.png\"></a>");
document.write("     </li>");
document.write("     <li class=\"line_right\">");
document.write("        <a href=\"\"><img src=\"./img/sbhq.png\"></a>");
document.write("     </li>");
document.write("     <li class=\"line_right\">");
document.write("        <a href=\"\"><img src=\"./img/znxg.png\"></a>");
document.write("     </li>");
document.write("     <li class=\"\">");
document.write("        <a href=\"\"><img src=\"./img/yzs.png\"></a>");
document.write("     </li>");
document.write("  </ul>");
document.write("</div>");
