document.write("<div class=\"_footer\">");
document.write("   <ul class=\"_width\">");
document.write("      <li class=\"_footer_lis fl\">");
document.write("         <ul>");
document.write("            <li  class=\"footer_title\">");
document.write("              关于我们");
document.write("            </li>");
document.write("            <li class=\"_lis_line\">");
document.write("               <ul>");
document.write("                  <li><a href=\"\">平台优势</a></li>");
document.write("                  <li><a href=\"\">媒体报道</a></li>");
document.write("                  <li><a href=\"\">团队介绍</a></li>");
document.write("                  <li><a href=\"\">招贤纳士</a></li>");
document.write("               </ul>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"_footer_lis fl\">");
document.write("         <ul>");
document.write("            <li class=\"footer_title\">");
document.write("              服务中心");
document.write("            </li>");
document.write("            <li class=\"_lis_line\">");
document.write("               <ul>");
document.write("                  <li><a href=\"\">联系我们</a></li>");
document.write("                  <li><a href=\"\">法律声明</a></li>");
document.write("                  <li><a href=\"\">免责条款</a></li>");
document.write("                  <li><a href=\"\">使用帮助</a></li>");
document.write("                  <li><a href=\"\">友情链接</a></li>");
document.write("               </ul>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"_footer_lis fl\">");
document.write("         <ul>");
document.write("            <li class=\"footer_title\">");
document.write("              商务合作");
document.write("            </li>");
document.write("            <li class=\"_lis_line\">");
document.write("               <ul>");
document.write("                  <li><a href=\"\">申请报道</a></li>");
document.write("                  <li><a href=\"\">金融服务</a></li>");
document.write("                  <li><a href=\"\">咨询服务</a></li>");
document.write("                  <li><a href=\"\">品牌活动</a></li>");
document.write("                  <li><a href=\"\">市场合作</a></li>");
document.write("               </ul>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"_footer_lis fl\">");
document.write("         <ul>");
document.write("            <li class=\"footer_title\">");
document.write("               内容合作");
document.write("            </li>");
document.write("            <li class=\"_lis_line\">");
document.write("               <ul>");
document.write("                  <li><a href=\"\">我要投稿</a></li>");
document.write("                  <li><a href=\"\">线索爆料</a></li>");
document.write("                  <li><a href=\"\">申请专栏</a></li>");
document.write("                  <li><a href=\"\">内容合作</a></li>");
document.write("               </ul>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"_enterprise fl\">");
document.write("         <img src=\"./img/logo1.png\" class=\"_logo1\">");
document.write("         <ul>");
document.write("            <li class=\"QR_code\">");
document.write("               <p>订阅号</p>");
document.write("               <img src=\"./img/dingyuehao.png\">");
document.write("            </li>");
document.write("            <li class=\"QR_code\">");
document.write("               <p>微博</p>");
document.write("               <img src=\"./img/weibo.png\">");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("   </ul>");
document.write("   <div class=\"_width\">");
document.write("      <a href=\"\">投资界</a>");
document.write("      <a href=\"\">证券时报</a>");
document.write("      <a href=\"\">联讯证券</a>");
document.write("      <a href=\"\">中信建投</a>");
document.write("   </div>");
document.write("</div>");
document.write("<div class=\"_last_content\">");
document.write("    <img src=\"./img/logo1.png\" style=\"width:87px;height:27px;\">");
document.write("    <span>&nbsp;Copyright  <span>©</span>易三板  版权所有 京ICP备 15028646号</span>");
document.write("</div>");
