document.write("<div class=\"box_right fr\">");
document.write("   <img src=\"./img/img4.png\" class=\"box_right_img\">");
document.write("   <ul class=\"box_right_ul1\">");
document.write("      <li class=\"_line_ccc box_right_ul1_li1\">");
document.write("         <span class=\"cp _line1\">市场总貌</span>");
document.write("         <span class=\"cp\">三板做市</span>");
document.write("         <span class=\"cp\">三板成指</span>");
document.write("         <a href=\"javascript:void(0);\" target=\"_blank\" class=\"_more fr\">更多</a>");
document.write("      </li>");
document.write("      <li class=\" box_right_ul1_li2\">");
document.write("         <ul>");
document.write("            <li class=\"_line_ccc\">");
document.write("               <span>挂牌公司：</span>");
document.write("               <span>11113</span>");
document.write("            </li");
document.write("            <li class=\"_line_ccc\">");
document.write("               <span>做市转让：</span>");
document.write("               <span>11113</span>");
document.write("            </li>");
document.write("            <li class=\"_line_ccc\">");
document.write("               <span>协议转让：</span>");
document.write("               <span>11113</span>");
document.write("            </li>");
document.write("            <li class=\"_line_ccc\">");
document.write("               <span>总股本&nbsp;&nbsp;：</span>");
document.write("               <span>6339.60</span>亿股");
document.write("            </li>");
document.write("            <li class=\"_line_ccc\">");
document.write("               <span>流通股本：</span>");
document.write("               <span>2775.05</span>亿股");
document.write("            </li>");
document.write("            <li class=\"_line_ccc\">");
document.write("               <span>成交金额：</span>");
document.write("               <span>45094.32</span>万元");
document.write("            </li>");
document.write("            <li class=\"_line_ccc\">");
document.write("               <span>成交股数：</span>");
document.write("               <span>1211212</span>万股");
document.write("            </li>");
document.write("            <li>");
document.write("               <span>截止日期：</span>");
document.write("               <span>2017-04-28</span>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <!-- /*三板快讯*/ -->");
document.write("      <li class=\"box_right_ul1_li3 _line_BD0708\">");
document.write("         <ul>");
document.write("            <li class=\"_line_ccc\">");
document.write("               三板快讯");
document.write("               <a href=\"javascript:void(0);\" class=\"_more fr\">更多</a>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <!-- 三板快讯的li列表 -->");
document.write("      <li class=\"box_right_ul1_li4\">");
document.write("         <ol>");
document.write("            <a href=\"http://www.w3school.com.cn/tags/att_li_type.asp\" target=\"_blank\">");
document.write("               <li>");
document.write("                  <p>夏栀言金：4.14复活节来临休市，下周黄金技术分析.</p>");
document.write("                  <div>两分钟前</div>");
document.write("               </li>");
document.write("            </a>");
document.write("            <a href=\"http://www.w3school.com.cn/tags/att_li_type.asp\" target=\"_blank\">");
document.write("               <li>");
document.write("                  <p>夏栀言金：4.14复活节来临休市，下周黄金技\术分析.</p>");
document.write("                  <div>两分钟前</div>");
document.write("               </li>");
document.write("            </a>");
document.write("            <a href=\"http://www.w3school.com.cn/tags/att_li_type.asp\" target=\"_blank\">");
document.write("               <li>");
document.write("                  <p>夏栀言金：4.14复活节来临休市，下周黄金技术分析.</p>");
document.write("                  <div>两分钟前</div>");
document.write("               </li>");
document.write("            </a>");
document.write("            <a href=\"http://www.w3school.com.cn/tags/att_li_type.asp\" target=\"_blank\">");
document.write("               <li>");
document.write("                  <p>夏栀言金：4.14复活节来临休市，下周黄金技术分析.</p>");
document.write("                  <div>两分钟前</div>");
document.write("               </li>");
document.write("            </a>");
document.write("         </ol>");
document.write("      </li>");
document.write("      <!-- 热点新闻 -->");
document.write("      <li class=\"box_right_ul1_li3 _line_BD0708\">");
document.write("         <ul>");
document.write("            <li class=\"_line_ccc\">");
document.write("               热点新闻");
document.write("               <a href=\"javascript:void(0);\" class=\"_more fr\" target=\"_blank\">更多</a>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"box_right_ul1_li6\">");
document.write("         <ul>");
document.write("            <li style=\"position:relative;\">");
document.write("               <a href=\"http://www.w3school.com.cn/tags/att_li_type.asp\"  target=\"_blank\">");
document.write("                  <img src=\"./img/img4.png\">");
document.write("                  <p >");
document.write("                     神州优车到底有什么猫腻？神州优车到底有什么猫腻？神州优车到底有什么猫腻？");
document.write("                  </p>");
document.write("               </a>");
document.write("            </li>");
document.write("            <li style=\"position:relative;\">");
document.write("               <a href=\"http://www.w3school.com.cn/tags/att_li_type.asp\" target=\"_blank\">");
document.write("                  <img src=\"./img/img4.png\">");
document.write("                  <p >");
document.write("                     神州优车到底有什么猫腻？神州优车到底有什么猫腻？神州优车到底有什么猫腻？");
document.write("                  </p>");
document.write("               </a>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"box_right_ul1_li7\">");
document.write("         <ul>");
document.write("            <li class=\"ul_li\">");
document.write("               <a href=\"\" target=\"_blank\">");
document.write("                  <img src=\"./img/img5.png\">");
document.write("                  <div class=\"fr\">");
document.write("                     <p class=\"_p\">夏栀言金：4.14复活节来临休市，下周黄金技术分析</p>");
document.write("                     <p class=\"_time\">1分钟前</p>");
document.write("                  </div>");
document.write("               </a>");
document.write("            </li>");
document.write("            <li class=\"ul_li\">");
document.write("               <a href=\"\" target=\"_blank\">");
document.write("                  <img src=\"./img/img5.png\">");
document.write("                  <div class=\"fr\">");
document.write("                     <p class=\"_p\">夏栀言金：4.14复活节来临休市，下周黄金技术分析</p>");
document.write("                     <p class=\"_time\">1分钟前</p>");
document.write("                  </div>");
document.write("               </a>");
document.write("            </li>");
document.write("            <li class=\"ul_li\">");
document.write("               <a href=\"\" target=\"_blank\">");
document.write("                  <img src=\"./img/img5.png\">");
document.write("                  <div class=\"fr\">");
document.write("                     <p class=\"_p\">夏栀言金：4.14复活节来临休市，下周黄金技术分析</p>");
document.write("                     <p class=\"_time\">1分钟前</p>");
document.write("                  </div>");
document.write("               </a>");
document.write("            </li>");
document.write("            <li class=\"ul_li\">");
document.write("               <a href=\"\" target=\"_blank\">");
document.write("                  <img src=\"./img/img5.png\">");
document.write("                  <div class=\"fr\">");
document.write("                     <p class=\"_p\">夏栀言金：4.14复活节来临\休市，下周黄金技术分析</p>");
document.write("                     <p class=\"_time\">1分钟前</p>");
document.write("                  </div>");
document.write("               </a>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <!-- 热门话题 -->");
document.write("      <li class=\"box_right_ul1_li3 _line_BD0708\">");
document.write("         <ul>");
document.write("            <li class=\"_line_ccc\">");
document.write("               热门话题");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"box_right_ul1_li8\">");
document.write("         <ul>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\" >新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("            <li class=\"fl\"><a href=\"\" target=\"_blank\">新三板</a></li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <!-- 新股挂牌 -->");
document.write("      <li class=\"box_right_ul1_li3 _line_BD0708\">");
document.write("         <ul>");
document.write("            <li class=\"_line_ccc\">");
document.write("               新股挂牌");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"box_right_ul1_li9\">");
document.write("         <ul>");
document.write("            <li class=\"_1234\">");
document.write("               <span class=\"cur_back_red\">1</span>");
document.write("               <span>2</span>");
document.write("               <span>3</span>");
document.write("               <span>4</span>");
document.write("            </li>");
document.write("            <li class=\"_detail\">");
document.write("               <span class=\"fl\">名称</span>");
document.write("               <span>转让方式</span>");
document.write("               <span class=\"fr\">日期</span>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("      <li class=\"box_right_ul1_li10 _line_BD0708_bottom\">");
document.write("         <ul>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("            <li>");
document.write("               <span class=\"fl\">联讯证券</span>");
document.write("               <span>做市</span>");
document.write("               <span class=\"fr\">2017-01-01</span>");
document.write("            </li>");
document.write("         </ul>");
document.write("      </li>");
document.write("   </ul>");
document.write("</div>");
